<?php

namespace Database\Factories;

use App\Models\Child;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class ChildFactory extends Factory
{
    protected $model = Child::class;
    public function definition()
    {        // Create a distribution of ages that will ensure we get all vaccination statuses
        $ageGroups = [
            'newborn' => ['start' => now()->subWeeks(4), 'end' => now(), 'weight' => 20],
            'middle_age' => ['start' => now()->subWeeks(40), 'end' => now()->subWeeks(4), 'weight' => 40],
            'older' => ['start' => now()->subWeeks(80), 'end' => now()->subWeeks(40), 'weight' => 40]
        ];

        $roll = $this->faker->numberBetween(1, 100);
        $dateRange = null;
        $sum = 0;

        foreach ($ageGroups as $group) {
            $sum += $group['weight'];
            if ($roll <= $sum) {
                $dateRange = ['start' => $group['start'], 'end' => $group['end']];
                break;
            }
        }
        return [
            'user_id' => \App\Models\User::factory(),
            // childNo will be automatically generated by the Child model based on date_of_birth
            'childName' => $this->faker->name(),
            'date_of_birth' => $this->faker->dateTimeBetween($dateRange['start'], $dateRange['end']),
            'gender' => $this->faker->randomElement(['male', 'female']),
            'birthWeight' => $this->faker->randomFloat(2, 2.0, 5.0),
            'birthHeight' => $this->faker->randomFloat(2, 40.0, 60.0),
            'fatherName' => $this->faker->name('male'),
            'motherName' => $this->faker->name('female'),
            'birthFacility' => $this->faker->company(),
            'birthAttendant' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
            'phoneNo' => $this->faker->randomElement(['255674960366', '255766418267', '255742795712', '255753303422', '255765814036', '255745456947']),
            'address' => [
                'street' => $this->faker->streetName(),
                'ward' => $this->faker->streetSuffix(),
                'Region' => $this->faker->state(),
            ],
            'motherAge' => $this->faker->numberBetween(18, 45),
        ];
    }
    public function configure()
    {
        return $this->afterCreating(function (Child $child) {
            // Vitamin and deworming records are now automatically created 
            // by the Child model's booted method, no need to create them here
        });
    }
}
